### ISSUE TITLE
Simulate authorization requests

### ISSUE THREAD

**Issue by leplatrem** [mozilla/doorman#53]
* Something like `/__simulate__`
* Post principals without JWT verification
* Basic Web UI

**Comment by leplatrem** [comment]
Idea:

Provide test files that would be executed out of the http request/response. 
They could be define in YAML as well:

```yaml
# policies_test.yaml
-
  principals:
    - userid: ldap|alice
    - group:hris_staff
  action:   create
  resource: pto
  policy:   staff-create-pto
  allowed:  true
-
  principals:
    - userid: ldap|alice
  action:   delete
  resource: article
  allowed:  false
-
  principals:
    - userid: ldap|alice
  action:   delete
  resource: article
  context:
    roles:
      - author
  allowed:  false

```
